### ISSUE TITLE
Can I translate this repository to another language like pt-br?

### ISSUE THREAD

**Issue by nkot56297** [drwshh/box-language#1]
Hi, drwshh!

My name is nkot56297!
I'm interested in this repository and would like to translate it into pt-br. I study about programming languages, I admire your work and would like to contribute by translating the repository to pt-br. If you grant this permission, I will make a pull request for it.

:)

regards,
nkot56297

**Comment by drwshh** [comment]
Hi, thanks for your interest.
Do you mean translating the readme file or the language itself?

**Comment by nkot56297** [comment]
Hi, thanks for answering.
I would like to translate the readme file.

**Comment by drwshh** [comment]
Sure 😀

**Comment by nkot56297** [comment]
Hi, thanks for answering.
So, can I make a pull request?

**Comment by drwshh** [comment]
Yes you can.

**Comment by nkot56297** [comment]
Hi, drwshh.
I submitted the pull request, hope it's all right. Could you give feedback if that's ok?

**Comment by drwshh** [comment]
It's good, thanks

**Comment by nkot56297** [comment]
Thank you for accepting the pull request; D
